name: IDECYDE
favicon: null
layout_spectrum: 0.75273
typography_spectrum: 0.728671370074153
title: ' Enterprise Applications Strategy '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffffe'
    - '#3e403f'
    - '#d68059'
    - '#88b97f'
    - '#00ffff'
  brandStrength: 0.5
  lightness: 0.12609678343869746
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
